[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_lottery = "89Kmtovb3JhuYirpLn6xJFANvHmwzVASRQ68KQWahuvy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/localnet-wallet.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

